#!/bin/bash

EXEC=$1
FNAME=$2
shift 2
ARGS="$*"
memcached -s vampire_mc_socket -m 512 -v &

#high timelimit because if we don't finish the theory loading, we're lost anyway
$EXEC $ARGS --mode ltb_build -t 120 < $FNAME




JOBS="`grep -v '^#' $FNAME | awk '
  BEGIN { fileSection=0; }
  /% SZS start BatchProblems/ { fileSection=1; }
  /% SZS end BatchProblems/ { fileSection=0; }
  /^[^%]/ { if(fileSection) { print $0 } }
' | tr ' ' ':' |sed 's/:*$//'`"

for JOB in $JOBS ; do
  INP=${JOB%%:*}
  OUTP=${JOB#*:}
  
  echo $INP
  $EXEC $ARGS --mode ltb_solve --input_file $INP |tee $OUTP
done 

kill %?memcached