#!/bin/bash

VAMPIRE='/raid/hoder/Dracula/vrel11'
EPROVER='/raid/hoder/eprover/PROVER/eprover'

$VAMPIRE $* |awk '
BEGIN { RS = "\n%#\n"; first=1; prev=0 }
{
	if( first==0 ) {
		curr=prev
		prev=$0
		if(curr!=0) {
			cmd="echo '\''" curr "'\'' |'$EPROVER' --tstp-in -s --cpu-limit=10 |grep  \"status Theorem\" "
			cmd_out=(cmd | getline)
#			print "============"
#			print cmd
#			print "------------"
#			print cmd_out
#			print
#			print
			if( !cmd_out ) {
				print "% '"$*"'"
				print "% failed:"
				print curr
				print
			}
			close(cmd)
		}
	}
	first=0
}
'
