#!/bin/bash
source AWS
cd $DOCKERS
sh build_satcomp_images.sh
TYPE="parallel"
if [ $# -eq 1 ] && [ $1 -ne 0 ]
then
        TYPE="cloud"
fi
cd $INFRASTRUCTURE
./create-solver-infrastructure --solver-type $TYPE
