#!/bin/bash

SCRIPT_DIR=`dirname $0`
BASE_DIR="$SCRIPT_DIR/.."


VAMPIRE="$BASE_DIR/vampire_rel"
#EPROVER='/raid/hoder/eprover/PROVER/eprover'
#OTHER_PROVER='/raid/hoder/vampire_old'
OTHER_PROVER="$VAMPIRE --time_limit 10 -ptb off -spl off"

$VAMPIRE --proof proofcheck $* |awk '
BEGIN { finished=0; curr=""; checkedCnt=0 }
END { print "checked steps: " checkedCnt }
{ special=0 }
/^Refutation found/ { special=1 }
/^%#/ {
	special=1
	if( curr!="" ) {
		cmd="echo '\''" curr "'\'' | sed -e \"s/\\\\\\$sk/xXsk/g\" -e \"s/\\\\\\$n/xXn/g\" -e \"s/\\\\\\$\\\\\\$e/xXeqProxy/g\" -e \"s/~!/~ !/g\" | '"$OTHER_PROVER"' /dev/stdin |grep \"^Refutation found\" "
		cmd_out=(cmd | getline)
		#print "============"
		#print cmd
		#print "============"
		#print $0
		#print "------------"
		print "cmd_out: " cmd_out
		#print
		#print
		if( !cmd_out ) {
			print "============"
#				print cmd
#				print "------------"
			print "% '"$*"'"
			print "% failed:"
			print curr
			print ""
		}
		close(cmd)
		checkedCnt++
		curr=""
	} else {
		finished=1
	}
}
special==0 && finished==0 {
	curr = curr "\n" $0
}
'
